### ISSUE TITLE
Full release of 0.8?

### ISSUE THREAD

**Issue by henryiii** [pypa/pyproject-metadata#104]
I've tested 0.8.0rc1 in scikit-build-core, and it seems good. Are we good for a 0.8.0 release? The only issue I see so far is a tiny typo in the changelog.

**Comment by henryiii** [comment]
Let's make sure https://github.com/pypa/pyproject-metadata/issues/30#issuecomment-2055707138 is resolved first.

**Comment by dnicolodi** [comment]
I would like to test it with meson-python. To fix most of the bugs the new release fixes, in meson-python have some overrides of pyproject-metadata methods. I would like to verify that things still work with the new code and that the new code fixes all issues so that we can drop the overrides in the next meson-python release. I can do this later today.

**Comment by dnicolodi** [comment]
Everything seems fine for meson-python. It would be nice to merge #109 included in the 0.8.0 release, but it is not a big deal.

**Comment by henryiii** [comment]
I've made RC 2. If no one sees issues, I'll probably make the full release tomorrow or so.

**Comment by rgommers** [comment]
Full release tomorrow SGTM. @dnicolodi's testing with `meson-python` covered things already, but to be doubly sure I tested `0.8.0rc2` with numpy, scipy and pywavelets - all seems happy.
