### ISSUE TITLE
Allow specifying dynamic fields after initial load

### ISSUE THREAD

**Issue by bennyrowland** [pypa/pyproject-metadata#51]
I am working on adding support for dynamic metadata to scikit-build-core. Currently I parse the metadata from the raw pyproject toml dict using pyproject-metadata, then loop over the fields listed as dynamic to work out what values need to be added in. This works nicely for `version` (and even removes it from the `dynamic` list, nice one), but doesn't work for other more complex fields like `readme` where the raw value gets parsed into an internal representation on initial load. At the moment the reading of the entry from pyproject and the parsing of the contents are tightly coupled in a single function, it would be great to split those out so that the readme (or whatever) can be provided later.

Ideally I would like to hook this into `__setattr__()` (as is already done for version) so that calling
`metadata.__setattr__("readme", {"content-type": rst, "text: "some generated text"})`
would just work. This would be nice as then I can loop over the fields in `dynamic` (`version`, `readme` etc.) without having to then dispatch to e.g. `set_version()`, `set_readme()` etc.

Does this fall within the intended scope of the package? If so then I would be very happy to put together a PR to add this functionality.

**Comment by henryiii** [comment]
I'm biased, but I'd be in favor. :)

**Comment by FFY00** [comment]
Yeah, I am not very happy with how this implemented, as it does not allow us to report all errors either. My plan is to move the parsing code to a function that can run for each field independently. With this approach, I could either make that function available for you to re-use, or have a hook to allow you to set the value of a field using raw metadata.

Is there any reason why you cannot simply provide the new metadata in our representation already? I did not consider your use-case initially because I didn't think anyone would actually need it, so I am wondering what I am missing.

**Comment by bennyrowland** [comment]
@FFY00 just a bump to see where we are with this issue
